// Authentications
export const AUTH_START   = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT  = 'AUTH_LOGOUT'
export const AUTH_REGISTRATION  = 'AUTH_REGISTRATION'
export const AUTH_REGISTRATION_FAIL    = 'AUTH_REGISTRATION_FAIL'
export const CAHNGE_PASSWORD = 'CHANGE_PASSWORD'
export const AUTH_LOGIN_FAIL    = 'AUTH_LOGIN_FAIL'
export const VERIFY_JWT_TOKEN = 'VERIFY_JWT_TOKEN'



// User profile 

export const LOGGEDIN_USER_INFO   = 'LOGGEDIN_USER_INFO'

export const SEND_INSTANT_EMAIL   = 'SEND_INSTANT_EMAIL'
export const SEND_INSTANT_EMAIL_FAIL   = 'SEND_INSTANT_EMAIL_FAIL'
export const SET_SEND_INSTANT_EMAIL   = 'SET_SEND_INSTANT_EMAIL'


export const SEND_EMAIL_WITH_TIMER   = 'SEND_EMAIL_WITH_TIMER'
export const SEND_EMAIL_WITH_TIMER_FAIL   = 'SEND_EMAIL_WITH_TIMER_FAIL'
export const SET_SEND_EMAIL_WITH_TIMER   = 'SET_SEND_EMAIL_WITH_TIMER'

export const GET_PEDNING_EMAIL   = 'SEND_EMAIL_WITH_TIMER_FAIL'
export const GET_ALL_THE_INSTALT_EMAIL   = 'SEND_EMAIL_WITH_TIMER_FAIL'
export const GET_ALL_EMAIL_SENT   = 'GET_ALL_EMAIL_SENT'
export const GET_ALL_EMAIL   = 'SEND_EMAIL_WITH_TIMER_FAIL'

export const GET_SINGEL_EMAIL   = 'GET_SINGEL_EMAIL'

export const EMAIL_UPDATE_SUCCESS   = 'EMAIL_UPDATE_SUCCESS'
export const UPDATE_EMAIL_UPDATE_SUCCESS_STATUS   = 'UPDATE_EMAIL_UPDATE_SUCCESS_STATUS'
export const EMAIL_UPDATE_ERROR   = 'EMAIL_UPDATE_ERROR'

export const EMAIL_DELETE_SUCCESS   = 'EMAIL_DELETE_SUCCESS'
export const UPDATE_EMAIL_DELETE_SUCCESS_STATUS   = 'UPDATE_EMAIL_DELETE_SUCCESS_STATUS'


export const GET_SENT_MAIL = 'GET_SENT_MAIL'
export const GET_SCHEDULE_MAIL = 'GET_SCHEDULE_MAIL'

export const UPDATE_ERROR_STATUS = 'UPDATE_ERROR_STATUS'



